name: CI/CD Pipeline

on:
  push:
    branches: [main, test]

jobs:
  install_dependencies:
    runs-on: self-hosted
    outputs:
      node_modules: ${{ steps.cache_node_modules.outputs.cache-hit }}
    defaults:
      run:
        working-directory: ${{ github.ref_name }}
    steps:
      - name: Set Environment Variables
        id: set-env
        run: |
          if [ "${{ github.ref_name }}" == "test" ]; then
            echo "CACHE_KEY=testing" >> $GITHUB_ENV
          else
            echo "CACHE_KEY=production" >> $GITHUB_ENV
          fi

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: ${{ github.ref_name }}

      - name: Cache npm dependencies
        id: cache_node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-admin-${{ env.CACHE_KEY }}-${{ hashFiles('${{ github.ref_name }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-admin-${{ env.CACHE_KEY }}

      - name: Install npm dependencies
        run: npm ci --legacy-peer-deps
        if: steps.cache_node_modules.outputs.cache-hit != 'true'

  tests:
    runs-on: self-hosted
    needs: install_dependencies
    defaults:
      run:
        working-directory: ${{ github.ref_name }}
    steps:
      - name: Run Linting
        run: npm run lint

      - name: Run Tests
        run: npm run test
        env:
          NEXT_PUBLIC_NEXT_ENV: ${{ github.ref_name == 'main' && 'production' || 'testing' }}
          NEXT_PUBLIC_API_URL: ${{ github.ref_name == 'main' && secrets.NEXT_PUBLIC_API_URL || secrets.NEXT_PUBLIC_API_URL_TEST }}
          NEXT_PUBLIC_WEB_URL: ${{ github.ref_name == 'main' && secrets.NEXT_PUBLIC_WEB_URL || secrets.NEXT_PUBLIC_WEB_URL_TEST }}
          PORT: ${{ github.ref_name == 'main' && secrets.PORT || secrets.PORT_TEST }}
          EMAIL: ${{ github.ref_name == 'main' && secrets.EMAIL || secrets.EMAIL_TEST }}
          PASSWORD: ${{ github.ref_name == 'main' && secrets.PASSWORD || secrets.PASSWORD_TEST }}
          PM2_NAME: ${{ github.ref_name == 'main' && secrets.PM2_NAME || secrets.PM2_NAME_TEST }}

  build:
    runs-on: self-hosted
    needs: tests
    defaults:
      run:
        working-directory: ${{ github.ref_name }}
    steps:
      - name: Build Application
        run: |
          rm -rf .next  # Clean up previous build artifacts
          npm run build  # Build the application
          pm2 restart "${{ github.ref_name == 'main' && secrets.PM2_NAME || secrets.PM2_NAME_TEST }}" || pm2 start pm2.config.cjs
          pm2 save
        env:
          NEXT_PUBLIC_NODE_ENV: ${{ github.ref_name == 'main' && 'production' || 'testing' }}
          NEXT_PUBLIC_API_URL: ${{ github.ref_name == 'main' && secrets.NEXT_PUBLIC_API_URL || secrets.NEXT_PUBLIC_API_URL_TEST }}
          NEXT_PUBLIC_WEB_URL: ${{ github.ref_name == 'main' && secrets.NEXT_PUBLIC_WEB_URL || secrets.NEXT_PUBLIC_WEB_URL_TEST }}
          PORT: ${{ github.ref_name == 'main' && secrets.PORT || secrets.PORT_TEST }}
          PM2_NAME: ${{ github.ref_name == 'main' && secrets.PM2_NAME || secrets.PM2_NAME_TEST }}

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy Application
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            DEPLOY_DIR="/var/www/admin"
          else
            DEPLOY_DIR="/var/www/manage"
          fi

          sudo cp -r ~/actions-runner-admin/_work/500kalima-cms/500kalima-cms/${{ github.ref_name }}/.next $DEPLOY_DIR/

      - name: Restart Nginx Service
        run: |
          sudo systemctl reload nginx
          sudo systemctl restart nginx